# Generated by Django 4.2.4 on 2023-10-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
        ('Funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='Empresa.empresa'),
            preserve_default=False,
        ),
    ]
