# Generated by Django 4.2.4 on 2023-10-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0003_funcionario_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtribuicaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pix', models.CharField(blank=True, max_length=50, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=255, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('operacao', models.CharField(blank=True, max_length=50, null=True)),
                ('agencia', models.CharField(blank=True, max_length=50, null=True)),
                ('conta', models.CharField(blank=True, max_length=50, null=True)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicao', to='Funcionario.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'E-mail')], max_length=10)),
                ('valor', models.CharField(max_length=100)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='Funcionario.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='Funcionario.funcionario')),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionariocontato',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='funcionarioendereco',
            name='funcionario',
        ),
        migrations.DeleteModel(
            name='FuncionarioAtribuicao',
        ),
        migrations.DeleteModel(
            name='FuncionarioContato',
        ),
        migrations.DeleteModel(
            name='FuncionarioEndereco',
        ),
    ]
