# Generated by Django 4.2.4 on 2023-10-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_endereco_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('fax', 'Fax'), ('celular', 'Celular')], max_length=10),
        ),
    ]
